require("telescope")

---@module "geometry"
local geometry = require "lib.geometry"

context("geometry", function()
  context("XYPoint", function()
    test("should be able to create a point", function()
      local point = geometry.XYPoint:new(10, 20)
      assert_equal(10, point:X())
      assert_equal(20, point:Y())
    end)
    test("should be able to convert a point to an array", function()
      local point = geometry.XYPoint:new(10, 20)
      local array = point:AsArray()
      assert_equal(10, array[1])
      assert_equal(20, array[2])
    end)
    test("should be able to unpack a point into variables", function()
      local point = geometry.XYPoint:new(10, 20)
      local x, y = point:Unpack()
      assert_equal(10, x)
      assert_equal(20, y)
    end)
    test("should be able to add two points together", function()
      local point1 = geometry.XYPoint:new(10, 20)
      local point2 = geometry.XYPoint:new(5, 15)
      local result = point1 + point2
      assert_equal(15, result:X())
      assert_equal(35, result:Y())
    end)
    test("should be able to subtract two points", function()
      local point1 = geometry.XYPoint:new(10, 20)
      local point2 = geometry.XYPoint:new(5, 15)
      local result = point1 - point2
      assert_equal(5, result:X())
      assert_equal(5, result:Y())
    end)
    test("should be able to add a scalar to a point", function()
      local point = geometry.XYPoint:new(10, 20)
      local result = point + 5
      assert_equal(15, result:X())
      assert_equal(25, result:Y())
    end)
    test("should be able to subtract a scalar from a point", function()
      local point = geometry.XYPoint:new(10, 20)
      local result = point - 5
      assert_equal(5, result:X())
      assert_equal(15, result:Y())
    end)
    test("should be able to multiply two points together", function()
      local point1 = geometry.XYPoint:new(10, 20)
      local point2 = geometry.XYPoint:new(5, 15)
      local result = point1 * point2
      assert_equal(50, result:X())
      assert_equal(300, result:Y())
    end)
    test("should be able to multiply a point by a scalar", function()
      local point = geometry.XYPoint:new(10, 20)
      local result = point * 2
      assert_equal(20, result:X())
      assert_equal(40, result:Y())
    end)
    test("should be able to divide a point by a scalar", function()
      local point = geometry.XYPoint:new(10, 20)
      local result = point / 2
      assert_equal(5, result:X())
      assert_equal(10, result:Y())
    end)
    test("should be able to divide a point by another point", function()
      local point1 = geometry.XYPoint:new(10, 20)
      local point2 = geometry.XYPoint:new(5, 10)
      local result = point1 / point2
      assert_equal(2, result:X())
      assert_equal(2, result:Y())
    end)
  end)
  context("Rectangle", function()
    test("should be able to create a rectangle", function()
      local rect = geometry.Rectangle:new(geometry.XYPoint:new(10, 20), geometry.XYPoint:new(30, 40))
      assert_equal(10, rect:Left())
      assert_equal(20, rect:Top())
      assert_equal(30, rect:Width())
      assert_equal(40, rect:Height())
    end)
    test("should be able to get the right and bottom edges of a rectangle", function()
      local rect = geometry.Rectangle:new(geometry.XYPoint:new(10, 20), geometry.XYPoint:new(30, 40))
      assert_equal(40, rect:Right())
      assert_equal(60, rect:Bottom())
    end)
    test("should be able to get the corners of a rectangle", function()
      local rect = geometry.Rectangle:new(geometry.XYPoint:new(10, 20), geometry.XYPoint:new(30, 40))
      local topLeft = rect:TopLeft()
      assert_equal(10, topLeft:X())
      assert_equal(20, topLeft:Y())
      local topRight = rect:TopRight()
      assert_equal(40, topRight:X())
      assert_equal(20, topRight:Y())
      local bottomRight = rect:BottomRight()
      assert_equal(40, bottomRight:X())
      assert_equal(60, bottomRight:Y())
      local bottomLeft = rect:BottomLeft()
      assert_equal(10, bottomLeft:X())
      assert_equal(60, bottomLeft:Y())
    end)
    test("should be able to get the center of a rectangle", function()
      local rect = geometry.Rectangle:new(geometry.XYPoint:new(10, 20), geometry.XYPoint:new(30, 40))
      local center = rect:Center()
      assert_equal(25, center:X())
      assert_equal(40, center:Y())
    end)
    test("should be able to add a point to a rectangle", function()
      local rect = geometry.Rectangle:new(geometry.XYPoint:new(10, 20), geometry.XYPoint:new(30, 40))
      local newRect = rect + geometry.XYPoint:new(5, 10)
      assert_equal(15, newRect:Left())
      assert_equal(30, newRect:Top())
      assert_equal(30, newRect:Width())
      assert_equal(40, newRect:Height())
    end)
    test("should be able to subtract a point from a rectangle", function()
      local rect = geometry.Rectangle:new(geometry.XYPoint:new(10, 20), geometry.XYPoint:new(30, 40))
      local newRect = rect - geometry.XYPoint:new(5, 10)
      assert_equal(5, newRect:Left())
      assert_equal(10, newRect:Top())
      assert_equal(30, newRect:Width())
      assert_equal(40, newRect:Height())
    end)
    test("should be able to create a rectangle from a center point and size", function()
      local center = geometry.XYPoint:new(25, 40)
      local size = geometry.XYPoint:new(30, 40)
      local rect = geometry.Rectangle.FromCenter(center, size)
      assert_equal(10, rect:Left())
      assert_equal(20, rect:Top())
      assert_equal(30, rect:Width())
      assert_equal(40, rect:Height())
    end)
    test("should be able to create a rectangle from a bottom center point and size", function()
      local bottomCenter = geometry.XYPoint:new(25, 60)
      local size = geometry.XYPoint:new(30, 40)
      local rect = geometry.Rectangle.FromBottomCenter(bottomCenter, size)
      assert_equal(10, rect:Left())
      assert_equal(20, rect:Top())
      assert_equal(30, rect:Width())
      assert_equal(40, rect:Height())
    end)
    test("should be able to create a rectangle from bounds", function()
      local leftTop = geometry.XYPoint:new(10, 20)
      local rightBottom = geometry.XYPoint:new(40, 60)
      local rect = geometry.Rectangle.FromBounds(leftTop, rightBottom)
      assert_equal(10, rect:Left())
      assert_equal(20, rect:Top())
      assert_equal(30, rect:Width())
      assert_equal(40, rect:Height())
    end)
    test("should be able to divide a rectangle into a grid of cells", function()
      local rect = geometry.Rectangle:new(geometry.XYPoint:new(1, 2), geometry.XYPoint:new(100, 100))
      local cells = rect:Divide(geometry.XYPoint:new(10, 20))
      local expectedWidth = 10
      -- 100 height divided by 20 = 20 rows of height 5 each
      local expectedHeight = 5
      assert_equal(20, #cells)
      assert_equal(10, #cells[1])
      for i, row in ipairs(cells) do
        assert_equal(10, #row)
        for j, cell in ipairs(row) do
          assert_equal(expectedWidth, cell:Width())
          assert_equal(expectedHeight, cell:Height())
          assert_equal(1 + (j - 1) * expectedWidth, cell:Left())
          assert_equal(2 + (i - 1) * expectedHeight, cell:Top())
        end
      end
    end)
    test("should be able to divide a rectangle into an array of vertical cells", function()
      local rect = geometry.Rectangle:new(geometry.XYPoint:new(1, 2), geometry.XYPoint:new(100, 100))
      local cells = rect:DivideHorizontally(10)
      assert_equal(10, #cells)
      for i, cell in ipairs(cells) do
        assert_equal(1, cell:Left())
        assert_equal(2 + (i - 1) * 10, cell:Top())
        assert_equal(100, cell:Width())
        assert_equal(10, cell:Height())
      end
    end)
    test("should be able to divide a rectangle into an array of horizontal cells", function()
      local rect = geometry.Rectangle:new(geometry.XYPoint:new(1, 2), geometry.XYPoint:new(100, 100))
      local cells = rect:DivideVertically(10)
      assert_equal(10, #cells)
      for i, cell in ipairs(cells) do
        assert_equal(1 + (i - 1) * 10, cell:Left())
        assert_equal(2, cell:Top())
        assert_equal(10, cell:Width())
        assert_equal(100, cell:Height())
      end
    end)
  end)
end)
