name: Build QPlug

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'

    - name: Run plugin compiler
      run: .\plugincompile\PLUGCC.exe "${{ github.event.repository.name }}" "${{ github.workspace }}\plugin.lua"
      shell: cmd

    - name: Upload compiled plugin
      uses: actions/upload-artifact@v7
      with:
        name: compiled-plugin
        path: ./*.qplug
