name: Build QPlug

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'

    - name: Run plugin compiler
      run: .\plugincompile\PLUGCC.exe "${{ github.event.repository.name }}" "${{ github.workspace }}\plugin.lua"
      shell: cmd

    - name: Upload compiled plugin
      uses: actions/upload-artifact@v7
      with:
        name: compiled-plugin
        path: ./*.qplug

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download compiled plugin
      uses: actions/download-artifact@v7
      with:
        name: compiled-plugin

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./*.qplug
